version: '3.7'
services:
  app:
    image: "wordpress:latest"
    volumes:
      - $PWD/html:/var/www/html
      - $PWD/plugins:/var/www/html/wp-content/plugins/

    environment:
      WORDPRESS_DB_PASSWORD: $PASSWORD
    links:
      - "db:mysql"
    ports:
      - "80:80"
  db:
    image: "mariadb:latest"
    volumes:
      - $PWD/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD
      MYSQL_DATABASE: wordpress
